### PR TITLE
Add an event for box placement

### PR DESCRIPTION
**Pull request by vinz243**
This commit adds an event that is fired everytime a box is placed on a tileentity. This allows me to create a hook so other mod can automate things

### CODE REVIEW

**Comment by vinz243** [comment]
I also added a quick refactor which should be useful for future development, performance and code consistency. It ensures that all mutations to a tile entity's boxes are properly made by encapsulazting everything behind `com.creativemd.littletiles.common.tileentity.TileEntityLittleTiles#updateTiles(java.util.function.Consumer<com.creativemd.littletiles.common.tileentity.MutableTiles>)` 

```java
	entry.getKey().updateTiles((tilesTe) -> {
               tilesTe.removeTiles(entry.getValue());
	});
```

**Comment by vinz243** [comment]
I finally removed the first event and added a more generic one that is fired everytime a tile updated

Most of the things seems to be working fine
Could you please merge this?

**Comment by vinz243** [comment]
~~It appeared thatthere might be an issue with loading tho.  It needs a fix~~ 

Edit : fixed it

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. First of all thank you very much for taking your time!

Your changes are quite massive for a simple event implementation. I like some but not all of the changes. The `te.updateTiles` one is pretty nice, but also pretty complex to upgrade. I would like to do it myself to make sure things don't get messed up (already saw a few things which are not supposed to be like that).

Also not sure about the new classes Tiles and MutableTiles, I don't really get the reason why you would need it.

**Comment by vinz243** [comment]
Hello, thank you for response. At first it seems to only require a few lines of code, but when I need to implement deletion it turned out I needed more.

The goal of the updateTiles method (and using a lamda) is to minimize the number of times the event is fired. If I fired the event every time the `tiles` list is updated, this could fire the event several time for a given operation. For example, if I removed a single box from a tileentity in MC the event would be fired when the `tiles`  list is cleared and then for a every box that was present before the clear, which would be very inefficient. This also simplifies write operation, so they don't need to access `preventUpdate` and handle this kind of things. It also help describe the aim of the code, highlighting the update operations. Finally, it allows to call the update rendering functions only after the code is executed and that all tiles have been changed.

I used two interfaces, Tiles and MutableTiles. There is only one class implementing both interfaces, so that the class itself stays simple and straightforward (implementing both read and write operations) while for external code you are not able to update tiles so easily. It allows to make wrong usage (updating tiles without calling updateTiles) look wrong (because you would need to cast it).

> already saw a few things which are not supposed to be like that

I'd be glad to help debugging. I already had a few trouble with null world.

**Comment by CreativeMD** [comment]
As I said I really like the updateTiles lambda method, but can you revert all changes where you attempted to fix the errors (caused by the new method)? I really like to break things and then fix it by hand to keep track of everything.

To be honest I don't want to change the TileEntity class that much at the moment. Furthermore I don't like the amount of classes and interfaces for one simple list of tiles. It would only be used for the TileEntity class anyway and nowhere else. So I would be happy if you could revert that part.

It also appears you use a different formatter. If you want to I can download mine (but there is no need for it, I can also format them after the pr): https://www.dropbox.com/s/ikb4hvxnowt4ubj/CreativeFormater.xml?dl=1

I'm sorry if I said a little bit harsh. I really appreciate your effort!

**Comment by vinz243** [comment]
I'm going to close this PR for now to create a new one that better expresses then intent of what I wanna do and answer to the questions

**Comment by CreativeMD** [comment]
BTW, what I forgot to mention is the basic idea to combine the 3 tiles list together, as it solve some synchronization issues (to keep track of render and update tiles properly). I will take some of your code `TilesImpl` rename to TileList and make some changes.

**Comment by CreativeMD** [comment]
If commited the TileList class: https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/tileentity/TileList.java

I will commit the remaining changes soon.

**Pull request closed without merging**
