### PR TITLE
Texture optimization

### PR DESCRIPTION
**Pull request by Desoroxxx**
So, I was bored, since I was bored, I just started optimizing the textures and saved up 8,618 bytes.
#### Just a little bit cool, but, let me calculate how much bandwidth I saved:
```
I saved 8,618 bytes so if we multiply it by, for example if 1000 people download the mod:
8618*1000=8618000
We get 8618000 bytes converted to megabyte it's 8.618 MB!
```
So, I saved 8.618 MB per 1000 download of the mod, **seems cool**.

### CODE REVIEW

**Comment by CreativeMD** [comment]
Are the textures still identical? Would be good to know what exactly you did.

**Comment by CreativeMD** [comment]
Still there?

**Comment by Desoroxxx** [comment]
Yes, I am using a lossless compression method, that why it won't optimize all texture and they won't get a -200% in size, I verified each one by hand.

**Comment by CreativeMD** [comment]
Thanks!

**Pull request merged**
