### PR TITLE
Add update event which is fired after TileEntityLittleTiles#updateTiles(Consumer) is called

### PR DESCRIPTION
**Pull request by vinz243**
This was the original point of the first PR I made. Could you please merge this to allow compatibility with external mods? And could you give me an update when a prerelease containing these changes is released on curseforge? I wasn't able to reproduce a working build without gradle.

Thanks in advance

### CODE REVIEW

**Comment by CreativeMD** [comment]
Why would you need an event?

**Comment by vinz243** [comment]
I am making a mod which automates most pattern construction by replicating block placement around say, an axis. For that I need to listen to events from LittleTiles to be able to replicate the blocks.

**Comment by CreativeMD** [comment]
To be honest I don't want to post an event every time the block updates. That's a little to much in my eyes. I would rather hand it differently.

How do you handle rotations and so on?

**Comment by vinz243** [comment]
I transform the cuboids point's coordinates using a simple rotation matrix.  If using events might not be optimal, maybe a public API?

**Comment by CreativeMD** [comment]
Sorry for not responding earlier. It's not that easy to do. It will be almost impossible to do it after something has changed, but it has to be integrated directly. LittleTiles has so called actions for everything (destroy, build, change color etc.), they can be reverted and so on ([place example](https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/action/block/LittleActionPlaceStack.java#L60)).

Pretty sure the best and easiest way to implement something like that would be to take the actions and apply them to each region (flipped). The thing is you can't flip actions, so I would have to do that. Just let me know if like this approach.

**Comment by vinz243** [comment]
This could be a good solution. If you don't want to manually update every action, I think I could easily refactor a little to allow for a standard method:

- finish segregating the tile entity class, that is to say extract an interface from the class the actions will use instead of the class
 - encapsulate the TileEntity access [on this line](https://github.com/CreativeMD/LittleTiles/blob/a18ce5e43149cd80823984092dbc1eed3f3c46b3/src/main/java/com/creativemd/littletiles/common/action/LittleAction.java#L246) to replace with a proxy that also offers to hook on the proxying system as a public API
 - inside my mod  create a different implementation of the interface that forwards tiles to one or more tile entities (transforming coordinates) and hook into the proxy. this would also allow me to get the player performing the action, which i was not able before

**Comment by CreativeMD** [comment]
Ok ... I did something. Here an example (make sure the class containing this method is registered on the `MinecraftForge.EVENT_BUS`).

```java
@SubscribeEvent
public void onAction(ActionEvent event) {
   // Assuming the center is in the center of the block, you can also change that
   LittleAbsoluteBox center = new LittleAbsoluteBox(yourCenterBlock); 

   LittleAction flippedAction = event.action.flip(Axis.X, center);
   if (flippedAction == null)
      return;

   // This is just a basic example of two mirrors (x, z) you can of course have less or more (y)
   List<LittleAction> followUps = new ArrayList<>();
   followUps.add(flippedAction);
   followUps.add(flippedAction.flip(Axis.Z, center));
   followUps.add(event.action.flip(Axis.Z, center));

   event.action.furtherActions = followUps;
}
```
So basically this event is fired for every action, the action is then flipped (not all actions support that) and be added to a list which will be executed afterwards.

I couldn't test this code, so I would be very happy if you could give it a try, you just need to hook up your center. There will be plenty of issue most likely, just report them I will try to fix them.

**Comment by CreativeMD** [comment]
Still there?

**Comment by vinz243** [comment]
I'm sorry I've been quite busy lately, started new things and haven't played MC for a while. I'll try to implement when I get the time but right now I set my mind to very different things. Plus with my full time job I'm not so eager to code as a hobby.

**Comment by CreativeMD** [comment]
No problem! Sounds very familiar, take your time.

**Comment by vinz243** [comment]
Ok, now with the lockdown I have some time to take a look.

- The action event is lacking some attributes, it would be nice if it contained the World entity and even better with the player responsible for the action. In case the latter is not possible, I would need at least the tile coordinates, so that I may find the player responsible for the action.
- `flip` seems good, but I have a more generic approach in my code where the position is transformed using matrices. I could circumvent this but I would also need access to more methods such as rotate, or flip around an axis instead of a plan. Anyway, I think a more generic approach could be used such as `action.transform` which would take a `UnaryOperator<LittleVec>` as a parameter and apply it to your tiles.

If making a transform method is too complicated, then I could get around with a method for flipping around an axis, and another one around a plan (like a mirror)

**Comment by CreativeMD** [comment]
On thing I should have mention from the beginning is that LittleTiles does all this stuff on client side only. Once it's placed it will be send to the server to process it. Nonetheless I added the player to the action event.

Not sure about your second suggestion. I have never worked with an UnaryOperator. So I have no idea how this should be done. Maybe you can help me there a little? Furthermore the methods provide a way to rotate it around a center. Just keep in mind it's not a good idea to work with double, that's why a center of a box is used. If you give me more information of how your center works I could write some code which converts it.

EDIT
Just realized I could raise those events on the server as well, if that works better for you.

**Comment by vinz243** [comment]
> On thing I should have mention from the beginning is that LittleTiles does all this stuff on client side only. Once it's placed it will be send to the server to process it. Nonetheless I added the player to the action event.

Thank you, that will help a lot !

> Not sure about your second suggestion. I have never worked with an UnaryOperator. So I have no idea how this should be done. Maybe you can help me there a little?

It's just a simple functionnal interface like this :

```java
interface UnaryOperator<T> {
    T apply(T t);
}
```

So basically, you would pass all your points (LittleVec3) through the provided UnaryOperator, which would return new coordinates for the new point. I'll give an example later;

The UnaryOperator implementation would vary according to what's needed, but it would correspond to simple mathematical operations, such as matrix multiplication/offseting etc..

If you want I can try and make a PR showing what could be done.


> Just keep in mind it's not a good idea to work with double, that's why a center of a box is used.

I've worked with C&B where each voxel coordinates where integers between 0 and 16. Let's say this applies here too for the sake of simplicity here is an example function (where v is the input LittleVec3) :

image

Applying this function the every coordinate of your tiles will flip the shape Z-wise. The +8 -8 is there to offset so that it is centered.

> EDIT
Just realized I could raise those events on the server as well, if that works better for you.

I don't do a lot of modding so I'm not sure what I would need in my case. With previous implementations (C&B for instance) it worked without thinking about it. But I guess either is fine anyway.

**Comment by CreativeMD** [comment]
Ok, so instead of a flip or rotation (with an enum), you would rather like to have a matrix? 
I can implement it, but it might need more time, because I have to implement it for a couple of classes.
What class should I use for the UnaryOperator?

EDIT
Not sure if it would make things easier. The methods I showed you above work perfectly (and I'm not sure if you need more).

The reason for a center box instead of simple coordinates is that they are not enough to define all possible rotation centers.

**Comment by vinz243** [comment]
> Ok, so instead of a flip or rotation (with an enum), you would rather like to have a matrix?

A matrix would be enough for now, but I think a more generic method that accepts any java function should cover anything and would be easier to implement.

> What class should I use for the UnaryOperator?

Well the UnaryOperator can be found in the JRE, so you only need to use `UnaryOperator<LittleVec3>`. However, creating a dedicated interface such as this one might be better in the long run

```java
interface TileTransform {
  LittleVec3 apply(LittleVec3 in);
}
```

> Not sure if it would make things easier. The methods I showed you above work perfectly 

You mean flip? My mod would require several transformations :

 - Rotation around Y axis
 - Flip around a plan
 - Mirror around an axis

And those transformation can be stacked (ie flip + 3x rotation would allow to build a tower with the minimal amount of effort, etc)

> The reason for a center box instead of simple coordinates is that they are not enough to define all possible rotation centers.

So you are saying that there can be an odd number of tiles, which is a full 1x1 block could contain 5x5 tiles?

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier.

Flip around a plan and mirror around an axis? Isn't that the same? Rotations can be done around every axis (but only 90°, 180° and 270° degree). A matrix implementation would be possible, but very time consuming to implement. I would rather convert the matrix to a collection of rotations and flips.

Could you create an example method you would like to call? Maybe show me the code which is responsible for the transformation?

**Comment by vinz243** [comment]
Hello, don't worry I've picked up C&B for now so there is really no hurry. 

Flipping around a plan or an axis is not the same. 
Here is around a plan:

```
o | o
* | *
* | *
```
Here is around an axis:

```
o   *
* . *
*   o
```

but it's basically a 180° rotation.

So I guess rotation and flip would be enough, although I'm not sure I understand what makes it more complicated. A matrix would cover all future cases, tho I'm not sure there would be

**Comment by CreativeMD** [comment]
Ok, I thought mirror and flip would be the same, which means flipped around a plane (axis). The second example is nothing else than a flip with two or three axis (planes). LittleTiles is quite complex which means I would have to change a lot of things in order to implement matrixes. Furthermore you can do everything with rotation and flips so I don't really see a point in the amount of work. All I need is to know which transformation to apply when. I could also get this information out of the matrix but that would be very messy.

**Comment by CreativeMD** [comment]
Are there still any plans to continue it? Otherwise I would close this pr.

**Comment by CreativeMD** [comment]
I will close it for now. If you still want to continue it just contact me again.

**Pull request closed without merging**
