### PR TITLE
RFG & Update `mcmod.info` & Update readme

### PR DESCRIPTION
**Pull request by Desoroxxx**
## This PR aims to make working on LittleTiles as painless as possible with the help of [RFG](https://github.com/GTNewHorizons/RetroFuturaGradle).

With this to work on LittleTiles you simply need to:
- Clone the repository
- Open in the IDE of your choice
- Run `setupDecompWorkspace` (Can be found under `Tasks > modded minecraft`)
- Once `setupDecompWorkspace` is done reload the Gradle project
- You can now code and test by using `Run Client` & `Run Server`

Once you want to build the mod simply use the `build` task in Gradle

When you need to change the version simply go into the `gradle.properties` file and change the `version` property, it will automatically update the version everywhere including in the jar name.

---

This PR's also update's the readme and the mcmod.info.

---

Another thing this PR addresses is the outdated mappings.

---

Tested this in real instances with lots of mods nothing broke tested with OptiFine Shaders and lots of other mods.

---

This should also theoretically fix compatibility with Albedo, although I did not test that due to me being on AMD and Albedo seems to just white screens on AMD for some reason.

*PS: Sorry for the big PR that spiral in every direction, just layer the groundwork for future more targeted and sane PR's*

### CODE REVIEW

**Comment by CreativeMD** [comment]
Sorry but I cannot change the mappings. There are a few people who use this repo for 1.12 and this would break all of their setups.

**Comment by Desoroxxx** [comment]
> Sorry but I cannot change the mappings. There are a few people who use this repo for 1.12 and this would break all of their setups.

Why would it, they should just use it as a dependency like any other mods and it would be just fine?

**Comment by Desoroxxx** [comment]
Also you can use a mod with different mappings than yours without any trouble

**Comment by CreativeMD** [comment]
I'm talking about dev environments. They would break with this change.

**Comment by Desoroxxx** [comment]
> I'm talking about dev environments. They would break with this change.

Do you mean people doing dev on LT directly?

**Comment by Desoroxxx** [comment]
Or do you mean people making addons for LT/using it as a dependency?

**Comment by CreativeMD** [comment]
People who use this repo in their workspace ... the name changes will be compiler errors for them. Simple as that.

**Comment by Desoroxxx** [comment]
> 

Why would that happen, I use mods in my workspaces that have different mapping versions every day and it's fine?
Even this uses Lux and other outdated mod that has lower mapping versions and it is fine, I do not see a scenario where this would break anything

**Comment by CreativeMD** [comment]
You can watch this video if you want to understand it:
https://www.youtube.com/watch?v=7Ahshi_QjM4

**Comment by Desoroxxx** [comment]
> You can watch this video if you want to understand it: https://www.youtube.com/watch?v=7Ahshi_QjM4

But this video is invalidated by this pr, they just need to clone the repository and follow again if they want to work on LT.
If they wish to use it in another mod then they can either use curse maven to download it via CF, or you can provide them with the source and dev jar.

**Comment by Desoroxxx** [comment]
Plus if they are using it as a dependency unless they update the dependency in their workspace they should not be impacted by this change

**Comment by CreativeMD** [comment]
There are people working on LittleTiles itself for 1.12. It would break their workspace and they would have to redo their stuff as well. Furthermore these curse maven dependencies have their issues as well. I have changed everything related to the setup for my mods in 1.18+ ... but I don't think it makes sense to break every current setup, especially 1.12 is at the end of its development lifecycle.

**Comment by Desoroxxx** [comment]
But it would not break any setup that's my point

**Comment by CreativeMD** [comment]
Because as soon as they pull the newest changes the new names won't match causing plenty of compiler errors.

**Comment by Desoroxxx** [comment]
> Because as soon as they pull the newest changes the new names won't match causing plenty of compiler errors.

But I already fixed the new changes, if you are talking about a mod like ALET it shouldn't directly use the raw source anymore, it should use the dev/source jar which will not cause any compiler errors.
Plus it will be way easier to handle for them.

**Comment by CreativeMD** [comment]
I don't see a reason to change this in 1.12. For further versions yes, but here it will create more issues than it solves.

**Comment by Desoroxxx** [comment]
> I don't see a reason to change this in 1.12. For further versions yes, but it will create more issues than it solves.

Again it should not create any issue there has been no logic changes it acts the same as the last version

**Comment by CreativeMD** [comment]
I appreciate your work and effort! I think adding a gradlew setup to this 1.12 repo is great, but not at the cost of breaking all existing workspaces. I explained my point several times. I understand that you do things different and therefore might not be able to relate why this is such an issue. If there is a way to add this gradle setup without changing the mapping at all (having no changes inside the src folder) I will merge it, otherwise I will not as I don't think it is worth all the troubles that come up with this.

**Pull request closed without merging**
